import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

export default function Home() {
  const session = useSession();

  if (session.status === "authenticated") {
    return (
      <div>
        <p>Signed in as {session.data?.user?.email}</p>
        <button
          className="w-40 bg-white p-2 text-black shadow-md"
          onClick={() => signOut()}
        >
          Sign out
        </button>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-xl">
        <div>Yo</div>
        <button
          className="w-40 bg-white p-2 text-black shadow-md"
          onClick={() => signIn()}
        >
          Sign in
        </button>
      </main>
    </>
  );
}
